### ISSUE TITLE
Add n^2  nested loop repl example

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/ruby-data-structures-algorithms-intro#2]

**Comment by thierrychau** [comment]
Is this different from the bubble sort example?

**Comment by heratyian** [comment]
> Is this different from the bubble sort example?

good point. I think I'll add a nested loop anyways for a super simple example. Trying to give folks a feel for what to look for / avoid. I might end up moving the sorting / searching examples somewhere else.

**Comment by heratyian** [comment]
#0ea58058c3e512350d432007cffc22dff4398baf closes
